import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import SignUp from "./components/SignUp";
import Search from "./components/search";
import Message from "./components/message";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <Search></Search>
                {/* <SignUp></SignUp> */}
                {children}
                {/* <Message /> */}
                <Footer />
            </body>
        </html>
    );
}
